autoencoder_weight: 0.01
dataset: texas
dropout: 0.3
fixed_threshold: 0.9
flex_batch: 64
flexmatch_weight: 0.8
gpu: 4
hidden_dim: 32
lr: 0.01
mask_edge_flag: false
metric: accuracy
model_name: mlp
momentum: 0.9
num_layers: 3
test_ratio: 0.25
train_ratio: 0.5
val_ratio: 0.25
weight_decay: 0.001
